

module koala{

//sequence<int>				IntList_t;
sequence<string> 			SIDS_t;
//dictionary<string,string> 	Properties_t;
//sequence<byte> 				StreamData_t;


//错误信息
struct Error_t{
	bool 	succ;		//成功标志
	int 	code;		//错误码
	string  msg;		//错误信息描述
};


//通用返回信息
struct CallReturn_t{
	Error_t error;		//错误信息
	string value;		//返回值
	string delta;		//额外参数
};

//时间范围
struct TimeRange_t{
    long start;		//开始
    long end;		//结束
};




//用户认证信息, AuthResult信息将被编码成Token并传递到前端
struct AuthToken_t{
    string 	user_id;			//用户编号
    string 	user_name;			//用户名称
    long    login_time;			//登陆时间
    long    expire_time;		//会话过期时间
    int    	platform_type;			//android,ios,desktop
    string 	device_id;			//设备编号,用于设备登陆到tgs时，tgs判断登陆设备与token是否一致
};


struct PushMessageStyle_t{
	int  builder_id;
	int  ring;
};

struct PushClickAction_t{
    int act_type;
    string  url;
    int conform_on_url;
    string activity;
    string intent;
    int    intent_flag;
    int    pending_flag;
    string    package_name;
    string   package_download_url;
    int   confirm_on_package;
};

struct PushMessage_t{
	string title;
	string content;
	string expire_time;
	string send_time;
	string accept_time;
	int    type;
    PushMessageStyle_t style;
    PushClickAction_t action;
    string custom;
    int loop_times;
    int loop_inerval;
    // for ios
    string alert;
    int  badge;
    string sound ;
    string category;
    string raw; 
};




struct Message_t{
	string seq;
	string sender_id;
    string send_time;

    string title;
	string content;
	int    type;
    PushMessageStyle_t style;
    PushClickAction_t action;
    string custom;

    // for ios
    string alert;
    int  badge;
    string sound ;
    string category;
    string raw;
};



// ITerminal 终端接口
interface ITerminal{
	void onMessage(Message_t message);
	void onReject(string errcode,string errmsg);
};

interface IUserEventListener{
    void onUserOnline(string userid,string tgs_id,int device);          //用户上线 device - 登陆设备类型 0 - unknown, 1 - mobile , 2 - desktop
    void onUserOffline(string userid,string tgs_id,int device);         //用户离线
};





}
//-- The End -----------------------------

