
import koala

module koala{

//IMessageServer - 消息服务器
interface IMessageServer {
	void sendMessage(SIDS_t token_list,Message_t message);
	void confirmMessage(SIDS_t seqs);
};


}
//-- The End -----------------------------

